# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171221_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Annonymous', max_length=200),
        ),
    ]
